app:
    resource: '@AppBundle/Controller/'
    type: annotation

dashboard:
    path: /
    defaults: { _controller: AppBundle:Dashboard:index }
    methods: [GET]

fields:
    path: /fields{trailingSlash}
    defaults: { _controller: AppBundle:Field:index, trailingSlash : "/" }
    methods: [GET]
    requirements: { trailingSlash : "[/]{0,1}" }

fields_create:
    path: /fields/create{trailingSlash}
    defaults: { _controller: AppBundle:Field:create, trailingSlash : "/" }
    methods: [GET, POST]
    requirements: { trailingSlash : "[/]{0,1}" }

fields_show:
    path: /fields/{id}{trailingSlash}
    defaults: { _controller: AppBundle:Field:show, trailingSlash : "/" }
    requirements: { trailingSlash : "[/]{0,1}", id: '\d+' }
    methods: [GET, POST]

areas:
    path: /areas{trailingSlash}
    defaults: { _controller: AppBundle:Area:index, trailingSlash : "/" }
    methods: [GET]
    requirements: { trailingSlash : "[/]{0,1}" }

areas_show:
    path: /areas/{id}{trailingSlash}
    defaults: { _controller: AppBundle:Area:show, trailingSlash : "/" }
    requirements: { trailingSlash : "[/]{0,1}", id: '\d+' }
    methods: [GET]

areas_create:
    path: /areas/create{trailingSlash}
    defaults: { _controller: AppBundle:Area:create, trailingSlash : "/" }
    methods: [GET, POST]
    requirements: { trailingSlash : "[/]{0,1}" }

reservoirs:
    path: /reservoirs{trailingSlash}
    defaults: { _controller: AppBundle:Reservoir:index, trailingSlash : "/" }
    methods: [GET, POST]
    requirements: { trailingSlash : "[/]{0,1}" }

inventories:
    path: /inventories{trailingSlash}
    defaults: { _controller: AppBundle:Inventory:index, trailingSlash : "/" }
    methods: [GET]
    requirements: { trailingSlash : "[/]{0,1}" }

seeds_create:
    path: /seeds/create{trailingSlash}
    defaults: { _controller: AppBundle:Inventory:seedCreate, trailingSlash : "/" }
    methods: [GET, POST]
    requirements: { trailingSlash : "[/]{0,1}" }

tasks:
    path: /tasks{trailingSlash}
    defaults: { _controller: AppBundle:Task:index, trailingSlash : "/" }
    methods: [GET]
    requirements: { trailingSlash : "[/]{0,1}" }

tasks_create:
    path: /tasks/create{trailingSlash}
    defaults: { _controller: AppBundle:Task:create, trailingSlash : "/" }
    methods: [GET, POST]
    requirements: { trailingSlash : "[/]{0,1}" }

tasks_show:
    path: /tasks/{id}{trailingSlash}
    defaults: { _controller: AppBundle:Task:show, trailingSlash : "/" }
    requirements: { trailingSlash : "[/]{0,1}", id: '\d+' }
    methods: [GET, POST]

plants:
    path: /plants{trailingSlash}
    defaults: { _controller: AppBundle:Plant:index, trailingSlash : "/" }
    methods: [GET]
    requirements: { trailingSlash : "[/]{0,1}" }

plants_create:
    path: /plants/create{trailingSlash}
    defaults: { _controller: AppBundle:Plant:create, trailingSlash : "/" }
    methods: [GET, POST]
    requirements: { trailingSlash : "[/]{0,1}" }

plants_show:
    path: /plants/{id}{trailingSlash}
    defaults: { _controller: AppBundle:Plant:show, trailingSlash : "/" }
    requirements: { trailingSlash : "[/]{0,1}", id: '\d+' }
    methods: [GET, POST]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
